[project]
name = "backend"
version = "0.1.0"
description = "Backend"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "pydantic",
    "browser-use",
    "openai"
]
